### ISSUE TITLE
Problème de SESSION 

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Interfaces-portfolio#1]
Après avoir été connecté, j'arrive dans la page de mise à jour, 

Après que je clique sur la page d'inscription et que je reviens vers la page de Mise à jour, 

celui-ci demande de nouveau mes login, comme-ci il ne se souvient pas de ma session, 

il n'y a pas encore de gestion de session?

**Comment by lahatra3** [comment]
Mes sincères éxcuses, je vais le régler. Pardon encore !!!

**Comment by lahatra3** [comment]
Merci beaucoup, je vais le corriger !!!
